#' plot.taxonsampling
#'
#' S3 method for plotting _taxonsampling_ objects output by [run_TS()]).
#'
#' @param object list object of class _taxonsampling_
#'                     (generated by [run_TS()])
#' @param ... other parameters to be passed down to specific
#'            plot functions (currently unused)
#'
#' @return Nothing (called for side effects)
#'
#' @method plot taxonsampling
#'
#' @export
#'
plot.taxonsampling <- function(object, ...)
{
  if(!("outputIDs" %in% names(object))){
    warning("outputIDs object not found in input list.")
    invisible(FALSE)
  }

  nodes <- object$nodes[object$nodes$id %in% object$outputIDs, ]
  nodes$pathString <- paste(object$ts.params$taxon,
                            nodes$parent,
                            nodes$id,
                            sep = "|")
  nodes <- data.tree::as.Node(nodes, pathDelimiter = "|")
  nodes <- data.tree::ToListExplicit(nodes, unname = TRUE)
  return(networkD3::radialNetwork(nodes))

}
