#' summary.taxonsampling
#'
#' S3 method for summarizing _taxonsampling_ objects output by [run_TS()]).
#'
#' @param x list object of class _taxonsampling_
#'                     (generated by [run_TS()])
#' @param ... other parameters to be passed down to specific
#'            summary functions (currently unused)
#'
#' @return Nothing (called for side effects)
#'
#' @method summary taxonsampling
#'
#' @export
#'
summary.taxonsampling <- function(x, ...)
{
  if("ts.params" %in% names(x) && is.list(x$ts.params)){
    message(rep("-", 70))
    message("Processed taxonsampling object returned by run_TS() with input parameters:")
    for (i in seq_along(names(x$ts.params))){
      if(is.null(x$ts.params[[i]])) x$ts.params[[i]] <- "NULL"
      message(names(x$ts.params)[i], ": ", x$ts.params[[i]])
    }
    message(rep("-", 70))
  }

  if("ts.params" %in% names(x) && is.list(x$ts.params)){
    message("Element 'ts.params':\tlist with ",
            length(x$ts.params), " elements")
  }

  if("nodes" %in% names(x) && is.data.frame(x$nodes)){
    message("Element 'nodes':\tdata frame [",
            paste(names(x$nodes), collapse = ", "),
            "]; ", nrow(x$nodes), " rows")
  }

  if("ids_df" %in% names(x) && is.data.frame(x$ids_df)){
    message("Element 'ids_df':\tdata frame [",
            paste(names(x$ids_df), collapse = ", "),
            "]; ", nrow(x$ids_df), " rows")
  }

  if("spp_df" %in% names(x) && is.data.frame(x$spp_df)){
    message("Element 'spp_df':\tdata frame [",
            paste(names(x$spp_df), collapse = ", "),
            "]; ", nrow(x$spp_df), " rows")
  }

  if("countIDs" %in% names(x) && is.vector(x$countIDs)){
    message("Element 'countIDs':\tvector with ",
            length(x$countIDs), " elements")
  }

  if("countSpp" %in% names(x) && is.vector(x$countSpp)){
    message("Element 'countSpp':\tvector with ",
            length(x$countSpp), " elements")
  }

  if("outputIDs" %in% names(x) && is.vector(x$outputIDs)){
    message("Element 'outputIDs':\tvector with ",
            length(x$outputIDs), " elements")
  }

  if("outputSeqs" %in% names(x) && is.list(x$outputSeqs)){
    message("Element 'outputSeqs':\tlist with ",
            length(x$outputSeqs), " elements")
  }

  invisible(NULL)
}
